package:
  name: q2-phylogeny
  version: "0.0.5"

source:
  fn: 0.0.5.zip
  url: https://github.com/qiime2/q2-phylogeny/archive/0.0.5.zip
  # md5: 
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - q2-phylogeny = q2-phylogeny:main
    #
    # Would create an entry point called q2-phylogeny that calls q2-phylogeny.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - scikit-bio
    - qiime >=2.0.5
    - q2-types >=0.0.5

  run:
    - python
    - setuptools
    - scikit-bio
    - qiime >=2.0.5
    - q2-types >=0.0.5

test:
  # Python imports
  imports:
    - q2_phylogeny
    - q2_phylogeny.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.qiime.org
  license: BSD
  summary: 'Create and work with Phylogenetic trees in QIIME 2.'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
