package:
  name: q2-dada2
  version: "0.0.5"

source:
  fn: 0.0.5.zip
  url: https://github.com/benjjneb/q2-dada2/archive/0.0.5.zip
  # md5: 
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - q2-dada2 = q2-dada2:main
    #
    # Would create an entry point called q2-dada2 that calls q2-dada2.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - qiime >=2.0.5
    - q2-types >=0.0.5
    - biom-format >=2.1.5,<2.2.0

  run:
    - python
    - setuptools
    - qiime >=2.0.5
    - q2-types >=0.0.5
    - biom-format >=2.1.5,<2.2.0

test:
  # Python imports
  imports:
    - q2_dada2

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: BSD-3-Clause
  summary: 'Apply DADA2 to generate denoised sequence variants. '
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
